# Generated by Django 3.0.8 on 2020-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
