# Generated by Django 3.0.8 on 2020-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsauth', '0002_auto_20200725_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
