# Generated by Django 3.0.8 on 2020-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsauth', '0003_user_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.URLField(default='http://qe0l8lesp.bkt.clouddn.com/1595858988624.jfif'),
        ),
    ]
